services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web1_db
      MYSQL_USER: web1_user
      MYSQL_PASSWORD: web1_password
    volumes:
      - db_data:/var/lib/mysql
    networks: [backend]

  web1:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_USER: web1_user
      DB_PASSWORD: web1_password
      DB_NAME: web1_db
      VIRTUAL_HOST: web1.pucavv.io.vn
      LETSENCRYPT_HOST: web1.pucavv.io.vn
      VIRTUAL_PORT: 8888
    expose:
      - "8888"
    depends_on:
      - db
    networks: [backend, proxy]

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.8-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy_certs:/etc/nginx/certs:ro
      - proxy_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: [proxy]

  acme-companion:
    image: nginxproxy/acme-companion:2.6.1
    restart: always
    environment:
      DEFAULT_EMAIL: admin@pucavv.io.vn
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - proxy_certs:/etc/nginx/certs
      - proxy_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks: [proxy]

volumes:
  db_data:
  proxy_certs:
  proxy_html:
  acme:

networks:
  proxy:
  backend:
