services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web1_db
      MYSQL_USER: web1_user
      MYSQL_PASSWORD: web1_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web1:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_USER: web1_user
      DB_PASSWORD: web1_password
      DB_NAME: web1_db
    ports:
      - "8888:8888"
    depends_on:
      - db

volumes:
  db_data:
