services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web1_db
      MYSQL_USER: web1_user
      MYSQL_PASSWORD: web1_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  web1:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_USER: web1_user
      DB_PASSWORD: web1_password
      DB_NAME: web1_db
      VIRTUAL_HOST: pucavv.io.vn
      LETSENCRYPT_HOST: pucavv.io.vn
    expose:
      - 8888
    depends_on:
      - db
    networks:
      - backend
      - proxy

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - proxy_certs:/etc/nginx/certs:ro
      - proxy_vhost:/etc/nginx/vhost.d:ro
      - proxy_html:/usr/share/nginx/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web1
    networks:
      - proxy

    acme-companion:
      image: nginxproxy/acme-companion
      restart: always
      environment:
        DEFAULT_EMAIL: admin@pucavv.io.vn
      volumes:
        - proxy_certs:/etc/nginx/certs
        - proxy_vhost:/etc/nginx/vhost.d
        - proxy_html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
      depends_on:
        - nginx
      networks:
        - proxy

volumes:
  db_data:
  proxy_certs:
  proxy_vhost:
  proxy_html:

networks:
  proxy:
  backend:
