services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web1_db
      MYSQL_USER: web1_user
      MYSQL_PASSWORD: web1_password
    volumes:
      - db_data:/var/lib/mysql
    networks: [backend]

  web1:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_USER: web1_user
      DB_PASSWORD: web1_password
      DB_NAME: web1_db
    expose:
      - "8888"
    depends_on:
      - db
    networks: [backend, proxy]

  nginx-proxy:
    build: nginx:mainline-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    networks: [proxy]

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-proxy
    command: certonly --webroot --webroot-path=/var/www/html --email test@pucavv.io.vn --agree-tos --no-eff-email --staging -d web1.pucavv.io.vn

volumes:
  db_data:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  proxy:
  backend:
